### ISSUE TITLE
[BUG] Modificar capacidad actual de un hospedaje

### ISSUE THREAD

**Issue by FranRossi** [agustinadisiot/isa2-m7a-06#14]
**Describa el error**
No se cuenta con la funcionalidad de modificar la capacidad un hospedaje en el front como se solicita en la primera entrega.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Haga click en iniciar sesión
2. Ingrese las credenciales de un administrador
3. Seleccione Hospedajes
4. No existe opción de modificación de capacidad de Hospedaje

**Comportamiento esperado**
Se debería de poder modificar la capacidad de un hospedaje. 

**Referencia a los requerimientos**
Modificar la capacidad actual de un hospedaje.

**Comment by IvanMonjardin** [comment]
Según lo hablado por el equipo, la funcionalidad esta bien implementada. 

Referncia a la letra: 

"el sistema no se debe manejar nada referente a la
capacidad de un hotel o las habitaciones en sí, solo se debe marcar cuando un hotel está sin
capacidad forma manual por los administradores"
